<script>
    var <?php
        $code = \HPS\Heartland\Model\Payment::CODE;
        /* @noEscape */ echo $code;
        ?>;
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'Magento_Ui/js/modal/alert'
    ],
        /*
            *  Heartland payment method model
            *
            *  @category    HPS
            *  @package     HPS_Heartland
            *  @author      Heartland Developer Portal <EntApp_DevPortal@e-hps.com>
            *  @copyright   Heartland (http://heartland.us)
            *  @license     https://github.com/hps/heartland-magento2-module/blob/master/LICENSE.md
            */

        /*browser:true*/
        /*global define*/
        function ($, magentoConfirm, magentoAlert) {
            'use strict';
            /**
                * Get the public key from HPS/Heartland/Controller/Hss/Pubkey.php as url configured based on HPS/Heartland/etc/frontend/routes.xml
                * if there is any form of error we disable the payment form
                *
                */
            $(document).ready(function ($) {
                $('#iframes').fadeOut();

                var $triggers = $('.token-delete-button');
                $triggers.click(function () {
                    var that = this;
                    var token = that.getAttribute('data-token') || '';
                    magentoConfirm({
                        title: 'Delete stored card',
                        content: 'Are you sure you want to delete the stored card?',
                        actions: {
                            confirm: function () {
                                return $.ajax({
                                    url: '<?php /* @noEscape */ echo $block->getBaseUrl() ?>/heartland/creditcard/delete?t=' + token,
                                    showLoader: true,
                                    context: $('#SavedCardsTable'),
                                    success: function (data) {
                                        if (that.parentNode && that.parentNode.parentNode) {
                                            that.parentNode.parentNode.remove();
                                        }

                                        magentoAlert({
                                            title: 'Delete stored card',
                                            content: 'Your saved card has been removed from our records'
                                        });
                                    }
                                });
                            },
                        }
                    });
                });
            });
        }
    );
</script>
<table id="SavedCardsTable">
    <caption>Stored Payments for this customer(if any)</caption>
    <tbody>
        <?php
        $hpsTokens = $block->getStoredCards();
        if (!empty($hpsTokens)) {
            foreach ($hpsTokens as $token) {
                $token['token_value'] = $token['heartland_storedcard_id'];
                unset($token['heartland_storedcard_id'], $token['dt'], $token['customer_id']);
                $ccTypeHPS = strtoupper($token['cc_type']);
                ?>
                <tr>
                    <td width="width:100px" > </td>
                    <th align="left" id="image_holder_<?php /* @noEscape */ echo $token['token_value'] ?>"><?php /* @noEscape */ echo $ccTypeHPS . ' ending in ' . $token['cc_last4']; ?><br />Expiring on <?php /* @noEscape */ echo $token['cc_exp_month'] . '/' . $token['cc_exp_year']; ?><span class="card-type-<?php /* @noEscape */ echo $token['cc_type'] ?>" /></th>
                    <td width="width:50px" >
                        <input class="token-delete-button"
                               data-token="<?= $token['token_value'] ?>"
                               style="color:red;font-size:
                               2em;background-color: transparent;border: none"
                               type="button"
                               value="X">
                    </td>
                </tr>

                <?php
            }
        } else {
            ?>
            <tr>
                <td width="width:100px">You have no saved cards</td></tr><?php
        }
        ?>
    </tbody>
</table>
