<?php

namespace HPS\Heartland\Block\Customer;


class CreditCards extends \Magento\Vault\Block\Customer\CreditCards {

    public $_template = 'HPS_Heartland::cards_list.phtml';

    /**
     * @return string
     */
    public function getType() {        
        return parent::getType(); // TODO: Change the autogenerated stub
    }

}
