<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */


namespace HPS\Heartland\Model\Order;
class Payment extends \Magento\Sales\Model\Order\Payment
{
    public
    function canCapture()
    {
        return true;
    }

    public
    function canVoid()
    {
        return true; // TODO: Change the autogenerated stub
    }
}
